### ISSUE TITLE
Importer for RSS-Feeds

### ISSUE THREAD

**Issue by pwilimzig** [ikuseiGmbH/smart-village-app-converter-xml2json#1]
https://flaeming365.de/category/orte/potsdam-mittelmark/stadt-bad-belzig/feed/ should be included as a "News"-Source.

**Comment by marcometz** [comment]
Das wird aber eher ein eigener Rss2Json-Converter oder? Das hat ja nicht wirklich etwas mit TMB direkt zu tun und könnte ja auch für andere RSS Quellen genutzt werden.
